"use client"
import { NavegateBar } from '@/components/NavegateBar/NavegateBar'
import './globals.css'
import type { Metadata } from 'next'
import { Saira } from 'next/font/google'

export const saira = Saira({
  weight: ['300', '400', '500', '600'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Capputeeno',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <NavegateBar />
        {children}
      </body>
    </html>
  )
}
