"use client"
import { NavegateBar } from '@/components/organisms/NavegateBar'
import './globals.css'
import type { Metadata } from 'next'
import { Saira } from 'next/font/google'
import { useEffect, useState } from 'react'

export const saira = Saira({
  weight: ['300', '400', '500', '600'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Capputeeno',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [loading, setLoading] = useState<boolean>(true)

  useEffect(() => {
    setLoading(true);

    setTimeout(() => {
      setLoading(false);
    }, 2000);
  }, [])

  return (
    <html lang="en">
      <body className={saira.className}>
        {loading ? (
          <div>
            <p>CARREGANDO...</p>
          </div>
        ) : (
          <>
            <header>
              <NavegateBar />
            </header>
            {children}
          </>
        )}
      </body>
    </html>
  )
}
